export const footerStyles = {
  footer: "bg-gray-900 text-white",
  container: "container mx-auto px-4 py-12",
  grid: "grid grid-cols-1 md:grid-cols-4 gap-8",
  logoSection: "col-span-1 md:col-span-2",
  title: "text-2xl font-bold mb-4",
  description: "text-gray-300 mb-6 max-w-md",
  socialContainer: "flex space-x-4",
  socialLink: "text-gray-300 hover:text-white transition-colors",
  socialIcon: "h-6 w-6",
  sectionTitle: "text-lg font-semibold mb-4",
  linksList: "space-y-2",
  link: "text-gray-300 hover:text-white transition-colors",
  contactInfo: "space-y-2 text-gray-300",
  contactItem: "flex items-center",
  contactIcon: "h-5 w-5 mr-2",
  divider: "border-gray-700 my-8",
  bottomSection: "flex flex-col md:flex-row justify-between items-center",
  copyright: "text-gray-300 text-sm",
  bottomLinks: "flex space-x-6 mt-4 md:mt-0",
  bottomLink: "text-gray-300 hover:text-white text-sm transition-colors",
};
