version: "3.8"

services:
  nextjs_staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asociatia_nextjs_staging
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - jarvis_network

networks:
  jarvis_network:
    external: true
